apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-ui-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-ui
  template:
    metadata:
      labels:
        app: client-ui
    spec:
      containers:
      - image: revanthacr.azurecr.io/react-express-mongo-app_ui
        name: container1
        imagePullPolicy: IfNotPresent
