apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-app-pv
spec:
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 1G
 hostPath:
   path: /tmp/mongo-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1G
  storageClassName: ""
