apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: container1
       # command:
       # - mongod
       # - "--bind_ip"
       # - "0.0.0.0"
      
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-vol
          mountPath: /data/db
      volumes:
      - name: mongo-vol
        persistentVolumeClaim:
          claimName: mongo-pvc

