apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - image: revanthacr.azurecr.io/react-express-mongo-app_api:v2
        name: container1
        ports: 
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: server-side-configs
